"""Setting up tables

Revision ID: 3111b35f56f7
Revises: 710099644638
Create Date: 2022-02-28 00:46:38.055144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3111b35f56f7'
down_revision = '710099644638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=True),
    sa.Column('floor_price', sa.Float(precision=10, asdecimal=5), nullable=True),
    sa.Column('count', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('one_day_volume', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('one_day_change', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('one_day_sales', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('one_day_average_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('seven_day_volume', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('seven_day_change', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('seven_day_sales', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('seven_day_average_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('thirty_day_volume', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('thirty_day_change', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('thirty_day_sales', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('thirty_day_average_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('total_volume', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('total_sales', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('total_supply', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('count', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('num_owners', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('average_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('num_reports', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('market_cap', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('floor_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('response_json', postgresql_json.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_collection',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'collection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_collection')
    op.drop_table('user')
    op.drop_table('history')
    op.drop_table('collection')
    # ### end Alembic commands ###
