"""Setting up history collection relationship

Revision ID: 654829a39836
Revises: e6dce906b080
Create Date: 2022-02-28 01:51:55.141144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654829a39836'
down_revision = 'e6dce906b080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
