"""Setting up history collection relationship

Revision ID: 8ddd912019f7
Revises: 6ac3292038bf
Create Date: 2022-02-28 12:25:10.740416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddd912019f7'
down_revision = '6ac3292038bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
