"""Setting up history collection relationship

Revision ID: b3637ceff174
Revises: 8ddd912019f7
Create Date: 2022-02-28 12:29:47.888709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3637ceff174'
down_revision = '8ddd912019f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
