"""Setting up tables

Revision ID: e6dce906b080
Revises: 
Create Date: 2022-02-28 01:37:40.175172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6dce906b080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=True),
    sa.Column('floor_price', sa.Float(precision=10, asdecimal=5), nullable=True),
    sa.Column('count', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('one_day_volume', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('one_day_change', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('one_day_sales', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('one_day_average_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('seven_day_volume', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('seven_day_change', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('seven_day_sales', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('seven_day_average_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('thirty_day_volume', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('thirty_day_change', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('thirty_day_sales', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('thirty_day_average_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('total_volume', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('total_sales', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('total_supply', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('count', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('num_owners', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('average_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('num_reports', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('market_cap', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.Column('floor_price', sa.Float(precision=10, asdecimal=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_collection',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_collection')
    op.drop_table('user')
    op.drop_table('history')
    op.drop_table('collection')
    # ### end Alembic commands ###
