"""Fixing relationships

Revision ID: ff9dedcec1a4
Revises: 654829a39836
Create Date: 2022-02-28 01:58:59.367059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9dedcec1a4'
down_revision = '654829a39836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('collection', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'history', 'collection', ['collection'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_column('history', 'collection')
    # ### end Alembic commands ###
