"""msh

Revision ID: 36c167c18b5f
Revises: e80fa9fbfbcc
Create Date: 2022-02-26 11:54:17.471694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c167c18b5f'
down_revision = 'e80fa9fbfbcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
