"""Added timestamps

Revision ID: 79b2bb3c0639
Revises: f7ae9f56afe8
Create Date: 2022-02-26 12:37:19.692932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b2bb3c0639'
down_revision = 'f7ae9f56afe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('collection', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_collection', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_collection', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_collection', 'updated_at')
    op.drop_column('user_collection', 'created_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('collection', 'updated_at')
    op.drop_column('collection', 'created_at')
    # ### end Alembic commands ###
