"""Added timestamps

Revision ID: f7ae9f56afe8
Revises: 36c167c18b5f
Create Date: 2022-02-26 12:30:34.160321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ae9f56afe8'
down_revision = '36c167c18b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('collection', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('collection', 'updated_at')
    op.drop_column('collection', 'created_at')
    # ### end Alembic commands ###
